language: node_js
node_js: node
after_success: npm run coverage

cache:
  directories:
    - node_modules

script:
- npm test -- --coverage

env:
  - CI=true
  - REACT_APP_API_BASE_URL="https://mysterious-garden-51929.herokuapp.com"

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master