language: node_js
node_js: node
cache:
  directories:
    - node_modules

script:
  - nyc npm test --coverage

env:
  - REACT_APP_API_BASE_URL="https://mysterious-garden-51929.herokuapp.com"

before_deploy:
  - npm install netlify-cli -g
  - npm run build

after_success:

deploy:
  provider: script
  script: netlify deploy -p build
  skip_cleanup: true
  on:
    repo: RowdyRuffBoysINC/RRB-client